#!/bin/bash
set -e

clear
echo "🚀 Starting Convoy Panel installer By Lorinplayz..."
echo ""

cat <<'EOF'
  _      ____  _____  _____ _   _   _____  _           __     ________
 | |    / __ \|  __ \|_   _| \ | | |  __ \| |        /\\ \   / /___  /
 | |   | |  | | |__) | | | |  \| | | |__) | |       /  \\ \_/ /   / / 
 | |   | |  | |  _  /  | | | . ` | |  ___/| |      / /\ \\   /   / /  
 | |___| |__| | | \ \ _| |_| |\  | | |    | |____ / ____ \| |   / /__ 
 |______\____/|_|  \_\_____|_| \_| |_|    |______/_/    \_\_|  /_____|
                                                                      
 🤍 Framework Installer - Youtube.com/@Lorinplayz
EOF

curl -fsSL https://get.docker.com/ | sh

mkdir -p /var/www/convoy
cd /var/www/convoy

curl -Lo panel.tar.gz https://github.com/convoypanel/panel/releases/latest/download/panel.tar.gz
tar -xzvf panel.tar.gz
chmod -R o+w storage/* bootstrap/cache/

cp .env.example .env
