#!/bin/bash

                                                                                                                           
 printf "${blue}  _      ____  _____  _____ _   _   _____  _           __     ________
 printf "${blue} | |    / __ \|  __ \|_   _| \ | | |  __ \| |        /\\ \   / /___  /
 printf "${blue} | |   | |  | | |__) | | | |  \| | | |__) | |       /  \\ \_/ /   / / 
 printf "${blue} | |   | |  | |  _  /  | | | . ` | |  ___/| |      / /\ \\   /   / /  
 printf "${blue} | |___| |__| | | \ \ _| |_| |\  | | |    | |____ / ____ \| |   / /__ 
 printf "${blue} |______\____/|_|  \_\_____|_| \_| |_|    |______/_/    \_\_|  /_____|
echo ""
echo "Copyright (c) 2022 Lorinplayz | root@lorin.exe"

sudo apt update && sudo apt upgrade -y
sudo apt install nano
nano pterobot.py # (PASTE THE CODE INSIDE)

curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
sudo apt install -y nodejs

apt install python3-pip
pip install discord

sudo npm install -g pm2
pm2 start pterobot.py

echo 'Your PteroBot is Ready Made By Lorinplayz'
