#!/bin/bash

# ASCII Art
echo -e "${YELLOW}"
cat << "EOF"

 __       ______   ______     ________  ___   __    ______   __       ________   __  __   ______     
/_/\     /_____/\ /_____/\   /_______/\/__/\ /__/\ /_____/\ /_/\     /_______/\ /_/\/_/\ /_____/\    
\:\ \    \:::_ \ \\:::_ \ \  \__.::._\/\::\_\\  \ \\:::_ \ \\:\ \    \::: _  \ \\ \ \ \ \\:::__\/    
 \:\ \    \:\ \ \ \\:(_) ) )_   \::\ \  \:. `-\  \ \\:(_) \ \\:\ \    \::(_)  \ \\:\_\ \ \  /: /     
  \:\ \____\:\ \ \ \\: __ `\ \  _\::\ \__\:. _    \ \\: ___\/ \:\ \____\:: __  \ \\::::_\/ /::/___   
   \:\/___/\\:\_\ \ \\ \ `\ \ \/__\::\__/\\. \`-\  \ \\ \ \    \:\/___/\\:.\ \  \ \ \::\ \/_:/____/\ 
    \_____\/ \_____\/ \_\/ \_\/\________\/ \__\/ \__\/ \_\/     \_____\/ \__\/\__\/  \__\/\_______\/ 
                                                                                                     
                                                                      
        Copyright (c) 2026 Lorinplayz | root@lorin.exe                                                                      
                          Ptero Bot                                            
                                
                                
EOF
echo -e "${NC}"
                                                                  
sudo apt update && sudo apt upgrade -y
sudo apt install nano
nano pterobot.py # (PASTE THE CODE INSIDE)

curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
sudo apt install -y nodejs

apt install python3-pip
pip install discord

sudo npm install -g pm2
pm2 start pterobot.py

echo 'Your PteroBot is Ready Made By Lorinplayz'
