#!/bin/bash
set -e

clear
echo "🚀 Starting PufferPanel Panel installer By Lorinplayz..."
echo ""
  _      ____  _____  _____ _   _   _____  _           __     ________
 | |    / __ \|  __ \|_   _| \ | | |  __ \| |        /\\ \   / /___  /
 | |   | |  | | |__) | | | |  \| | | |__) | |       /  \\ \_/ /   / / 
 | |   | |  | |  _  /  | | | . ` | |  ___/| |      / /\ \\   /   / /  
 | |___| |__| | | \ \ _| |_| |\  | | |    | |____ / ____ \| |   / /__ 
 |______\____/|_|  \_\_____|_| \_| |_|    |______/_/    \_\_|  /_____|
                                                                      
 🤍 Framework Installer - github.com/Lorinplayz/

sudo apt update
sudo apt-get install pufferpanel

sudo pufferpanel user add


apt update

apt install sudo

apt install systemctl

apt upgrade

curl -s https://packagecloud.io/install/repositories

echo ""
echo "✅ Installation complete"
echo "➡️ Start with: node ."
